/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardJobsRouteImport } from './routes/_dashboard/jobs'
import { Route as DashboardInstancesRouteImport } from './routes/_dashboard/instances'
import { Route as DashboardAppsRouteImport } from './routes/_dashboard/apps'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstancesRoute = DashboardInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/apps': typeof DashboardAppsRoute
  '/instances': typeof DashboardInstancesRoute
  '/jobs': typeof DashboardJobsRoute
  '/users': typeof DashboardUsersRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/apps': typeof DashboardAppsRoute
  '/instances': typeof DashboardInstancesRoute
  '/jobs': typeof DashboardJobsRoute
  '/users': typeof DashboardUsersRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_dashboard/apps': typeof DashboardAppsRoute
  '/_dashboard/instances': typeof DashboardInstancesRoute
  '/_dashboard/jobs': typeof DashboardJobsRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/apps'
    | '/instances'
    | '/jobs'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/login' | '/apps' | '/instances' | '/jobs' | '/users' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/about'
    | '/login'
    | '/_dashboard/apps'
    | '/_dashboard/instances'
    | '/_dashboard/jobs'
    | '/_dashboard/users'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/jobs': {
      id: '/_dashboard/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/instances': {
      id: '/_dashboard/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof DashboardInstancesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps': {
      id: '/_dashboard/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppsRoute: typeof DashboardAppsRoute
  DashboardInstancesRoute: typeof DashboardInstancesRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppsRoute: DashboardAppsRoute,
  DashboardInstancesRoute: DashboardInstancesRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
